Ruff mypy fixes
CAREamics/careamics-restoration pull request #50
Opened 2023-07-18 16:34 UTC by CatEek

2023-07-18 18:42 UTC, jdeschamps commented
Is this branch superseeding https://github.com/CAREamics/careamics-restoration/pull/46 ?

2023-07-18 18:48 UTC, jdeschamps approved these changes

2023-07-18 18:50 UTC, jdeschamps commented
The tests are not passing

2023-07-18 18:52 UTC, jdeschamps requested changes
In engine.py:65:

```python
config, model, state_dict=checkpoint
```

The smoke test gives the following error:
```
E       UnboundLocalError: local variable 'model' referenced before assignment
```

2023-07-18 18:57 UTC, jdeschamps requested changes
Due to changes to what the configuration model represents (path vs file name), the fixture in `conftest.py` are causing errors in the tests.

Check the `complete_config`

2023-07-18 19:01 UTC, jdeschamps requested changes
The tests relative to the model path in the Configuration are not passing. Most seem to be comparing a `Path` to a `str`.

2023-07-18 19:54 UTC, CatEek commented on src/careamics_restoration/dataset/tiling.py
> +) -> Iterable[Tuple[np.ndarray[Any, np.dtype[Any]], bool, Tuple[int, ...], Any, Any]]:
Will take a look tomorrow

2023-07-19 15:35 UTC, jdeschamps approved these changes

2023-07-19 15:37 UTC, merged